[package]
name = "basic2_webapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
actix-web = "4.3.1"
busybody = { path = "../../" }
chrono = "0.4.26"
rand = "0.8.5"
